### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by YARE0909**
Finish Up Landing Page

Desktop:
image
image

Mobile:
Screen Shot 2023-11-05 at 00 16 29
Screen Shot 2023-11-05 at 00 17 09

### CODE REVIEW

**Comment by whiletrueee** [comment]
## Mobile view changes
> decrease the font size in general and at some specific points
image
image

> fix the border radius and padding
image


> decrease the button size 
image

check footer as well for font size

**Comment by whiletrueee** [comment]
## desktop view changes

> gap below image
image

> footer logo
image

> sticky navbar with shadow
image

>

**Comment by whiletrueee** [comment]
## How it should be

> it should be like this
image
image

**Review by shawshankkumar — APPROVED** [review]
merging right now, get the fixes done

**Pull request merged**
